### ISSUE TITLE
arsinh(tanh) or arsinh(tan) ?

### ISSUE THREAD

**Issue by ekspla** [330k/line_simplify_demo#1]
Mercator 変換で asinh(tanh) が  asinh(tan) の替わりに使われているようですが、どういう理由でしょうか？[gpx_tools](https://github.com/330k/gpx_tools) & [line_simplify_demo](https://github.com/330k/line_simplify_demo)

  tan の北極・南極付近の挙動を避けるためかも知れないと考えたのですが、関数値の違いも大きいように思います。RDP の目的だけ考えれば、適当な優先順位がつけられればそれでよいのかもしれないのですが、実際のデータ（SR600_Tsurugi.gpx）でもほんの少しですが結果が変わるようです。（そもそも２次元の Mercator 変換で細かいことを言っても仕方が無いのですが。）なにかノウハウのようなものがあるのかも知れないと思いました。お教えください。

**Comment by 330k** [comment]
あれ？単純にミスですね。ずっと前のミスを引きずっているようです。修正します。
ありがとうございます。

**Comment by ekspla** [comment]
早速のお返事ありがとうございます。承知しました。
